chore: storybook 빌드 압축파일 확인

diff --git a/.github/workflows/storybook-preview.yml b/.github/workflows/storybook-preview.yml
--- a/.github/workflows/storybook-preview.yml
+++ b/.github/workflows/storybook-preview.yml
@@ -27,6 +27,10 @@ jobs:
       - name: Archive
         run: tar -czf storybook.tar.gz -C storybook-static .
 
+      - name: Check storybook.tar.gz existence
+        run: |
+          ls -lh storybook.tar.gz || (echo "❌ storybook.tar.gz not found!" && exit 1)
+
       - name: Prepare SSH key
         run: |
           echo "${{ secrets.SERVER_SSH_KEY }}" > private_key
